// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/base/auth/wxlogin": {
            "get": {
                "description": "微信授权登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "微信授权登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户apiid",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/base.User"
                        }
                    }
                }
            }
        },
        "/base/upload": {
            "post": {
                "description": "上传接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基础模块"
                ],
                "summary": "上传接口",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/base.FileInfo"
                        }
                    }
                }
            }
        },
        "/base/users": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "用户列表接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "用户列表",
                "parameters": [
                    {
                        "type": "string",
                        "format": "email",
                        "description": "username search by q",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/base.User"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "用户注册接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "注册接口",
                "parameters": [
                    {
                        "description": "需要上传的json",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RegisterForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/base.User"
                        }
                    }
                }
            }
        },
        "/base/users/info": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "用户信息接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/base.User"
                        }
                    }
                }
            }
        },
        "/base/users/login": {
            "post": {
                "description": "用户登录接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "登录接口",
                "parameters": [
                    {
                        "description": "需要上传的json",
                        "name": "LoginForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResType"
                        }
                    }
                }
            }
        },
        "/base/users/password": {
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "修改密码接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "description": "需要上传的json",
                        "name": "LoginForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ChangePassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResType"
                        }
                    }
                }
            }
        },
        "/base/users/{id}": {
            "delete": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "删除用户接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/base.User"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "修改用户接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "修改用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User.ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "需要上传的json",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.UpdateUser"
                        }
                    }
                }
            }
        },
        "/mobile/chat/friends": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "好友列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "聊天模块"
                ],
                "summary": "好友列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User.ID",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResType"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "添加好友或加入群聊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "聊天模块"
                ],
                "summary": "添加好友关系",
                "parameters": [
                    {
                        "description": "需要上传的json",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AddFriend"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.AddFriend"
                        }
                    }
                }
            }
        },
        "/mobile/chat/friends/{friendId}": {
            "delete": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "删除好友",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "聊天模块"
                ],
                "summary": "删除好友",
                "parameters": [
                    {
                        "type": "string",
                        "description": "好友id",
                        "name": "friendId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResType"
                        }
                    }
                }
            }
        },
        "/mobile/chat/groupMembers": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "群成员列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "聊天模块"
                ],
                "summary": "群成员列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ChatGroup.ID",
                        "name": "groupId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResType"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "添加群成员",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "聊天模块"
                ],
                "summary": "添加群成员",
                "parameters": [
                    {
                        "description": "需要上传的json",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ChatGroupMember"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ChatGroupMember"
                        }
                    }
                }
            }
        },
        "/mobile/chat/groupMembers/{groupId}": {
            "delete": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "退出群聊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "聊天模块"
                ],
                "summary": "退出群聊",
                "parameters": [
                    {
                        "type": "string",
                        "description": "需要上传的json",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResType"
                        }
                    }
                }
            }
        },
        "/mobile/chat/groups": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "群组列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "聊天模块"
                ],
                "summary": "群组列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User.ID",
                        "name": "userId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Group.groupName",
                        "name": "groupName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResType"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "创建群聊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "聊天模块"
                ],
                "summary": "创建群聊",
                "parameters": [
                    {
                        "description": "需要上传的json",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ChatGroup"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ChatGroup"
                        }
                    }
                }
            }
        },
        "/mobile/chat/groups/{groupId}": {
            "delete": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "删除群聊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "聊天模块"
                ],
                "summary": "删除群聊",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群组id",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResType"
                        }
                    }
                }
            }
        },
        "/mobile/chat/logs": {
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "聊天记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "聊天模块"
                ],
                "summary": "聊天记录",
                "parameters": [
                    {
                        "description": "需要上传的json",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ChatLogQuery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ChatLog"
                            }
                        }
                    }
                }
            }
        },
        "/mobile/chat/updateReadTime": {
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "更新上次阅读信息时间",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "聊天模块"
                ],
                "summary": "更新阅读时间",
                "parameters": [
                    {
                        "description": "需要上传的json",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateReadTime"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "/mobile/moments": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "动态列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "动态模块"
                ],
                "summary": "动态列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "page",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResType"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "发动态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "动态模块"
                ],
                "summary": "发动态",
                "parameters": [
                    {
                        "description": "需要上传的json",
                        "name": "addMoment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AddMoment"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.AddMoment"
                        }
                    }
                }
            }
        },
        "/mobile/moments/UpdateMoment": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "更新点赞或者浏览数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "动态模块"
                ],
                "summary": "更新动态数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Moment.ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "like或者view",
                        "name": "t",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResType"
                        }
                    }
                }
            }
        },
        "/third/chatGPT": {
            "post": {
                "description": "chatGPT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "第三方模块"
                ],
                "summary": "chatGPT",
                "parameters": [
                    {
                        "description": "例子：为对话聊天机器人配置",
                        "name": "chatGPT",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/base.ChatGPT"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/base.ChatGPT"
                        }
                    }
                }
            }
        },
        "/third/gushici": {
            "get": {
                "description": "今日古诗词",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "第三方模块"
                ],
                "summary": "今日古诗词",
                "parameters": [
                    {
                        "type": "string",
                        "description": "立即刷新古诗词",
                        "name": "refresh",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/base.Third"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "base.ChatGPT": {
            "type": "object",
            "properties": {
                "frequencyPenalty": {
                    "type": "number",
                    "example": 0
                },
                "maxTokens": {
                    "description": "返回文本长度",
                    "type": "integer",
                    "example": 150
                },
                "model": {
                    "type": "string",
                    "example": "text-davinci-003"
                },
                "presencePenalty": {
                    "type": "number",
                    "example": 0.6
                },
                "prompt": {
                    "type": "string",
                    "example": "介绍一下自己"
                },
                "suffix": {
                    "description": "返回文本后缀",
                    "type": "string",
                    "example": "小夏"
                },
                "temperature": {
                    "description": "随机性程度",
                    "type": "number",
                    "example": 0.9
                },
                "topP": {
                    "type": "number",
                    "example": 1
                }
            }
        },
        "base.FileInfo": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "base.Third": {
            "type": "object"
        },
        "base.User": {
            "type": "object",
            "required": [
                "userName"
            ],
            "properties": {
                "avatar": {
                    "description": "用户头像",
                    "type": "string",
                    "example": "https://******.com/aa.png"
                },
                "createdAt": {
                    "description": "创建时间",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.JsonTime"
                        }
                    ]
                },
                "email": {
                    "description": "邮箱",
                    "type": "string",
                    "example": "123456789@qq.com"
                },
                "gender": {
                    "description": "性别",
                    "type": "integer"
                },
                "id": {
                    "description": "自增id",
                    "type": "integer"
                },
                "intro": {
                    "description": "个人介绍",
                    "type": "string",
                    "example": "个人介绍"
                },
                "isAdmin": {
                    "description": "是否管理员",
                    "type": "boolean",
                    "default": false
                },
                "isLock": {
                    "description": "是否已锁",
                    "type": "boolean",
                    "default": false
                },
                "nickName": {
                    "description": "用户昵称",
                    "type": "string",
                    "example": "酱"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.JsonTime"
                        }
                    ]
                },
                "userId": {
                    "description": "用户唯一id",
                    "type": "string"
                },
                "userName": {
                    "description": "用户名",
                    "type": "string",
                    "maxLength": 12,
                    "minLength": 4,
                    "example": "test"
                }
            }
        },
        "model.AddFriend": {
            "type": "object",
            "properties": {
                "friendId": {
                    "type": "string"
                },
                "groupId": {
                    "type": "integer"
                },
                "lastReadTime": {
                    "$ref": "#/definitions/model.JsonTime"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "model.AddMoment": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "urls": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "model.ChangePassword": {
            "type": "object",
            "required": [
                "newPassword",
                "password",
                "userName"
            ],
            "properties": {
                "newPassword": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 6,
                    "example": "123456"
                },
                "password": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 6,
                    "example": "123456"
                },
                "userName": {
                    "type": "string",
                    "maxLength": 12,
                    "minLength": 4,
                    "example": "test"
                }
            }
        },
        "model.ChatGroup": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "创建时间",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.JsonTime"
                        }
                    ]
                },
                "groupName": {
                    "type": "string"
                },
                "id": {
                    "description": "自增id",
                    "type": "integer"
                },
                "intro": {
                    "type": "string"
                },
                "notice": {
                    "type": "string"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.JsonTime"
                        }
                    ]
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "model.ChatGroupMember": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "创建时间",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.JsonTime"
                        }
                    ]
                },
                "groupId": {
                    "type": "integer"
                },
                "id": {
                    "description": "自增id",
                    "type": "integer"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.JsonTime"
                        }
                    ]
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "model.ChatLog": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "description": "创建时间",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.JsonTime"
                        }
                    ]
                },
                "groupId": {
                    "type": "integer"
                },
                "id": {
                    "description": "自增id",
                    "type": "integer"
                },
                "logType": {
                    "type": "integer"
                },
                "msgType": {
                    "type": "integer"
                },
                "receiverId": {
                    "type": "string"
                },
                "senderId": {
                    "type": "string"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.JsonTime"
                        }
                    ]
                },
                "userInfo": {
                    "$ref": "#/definitions/model.User"
                }
            }
        },
        "model.ChatLogQuery": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": ""
                },
                "groupId": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "pageSize": {
                    "type": "integer",
                    "example": 20
                },
                "receiverId": {
                    "type": "string"
                },
                "senderId": {
                    "type": "string"
                }
            }
        },
        "model.JsonTime": {
            "type": "object",
            "properties": {
                "time.Time": {
                    "type": "string"
                }
            }
        },
        "model.LoginForm": {
            "type": "object",
            "required": [
                "password",
                "userName"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 6,
                    "example": "123456"
                },
                "userName": {
                    "type": "string",
                    "maxLength": 12,
                    "minLength": 4,
                    "example": "test"
                }
            }
        },
        "model.RegisterForm": {
            "type": "object",
            "required": [
                "password",
                "userName"
            ],
            "properties": {
                "avatar": {
                    "description": "用户头像",
                    "type": "string",
                    "example": "https://******.com/aa.png"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string",
                    "example": "123456789@qq.com"
                },
                "gender": {
                    "description": "性别",
                    "type": "integer"
                },
                "intro": {
                    "description": "个人介绍",
                    "type": "string",
                    "example": "个人介绍"
                },
                "nickName": {
                    "description": "用户昵称",
                    "type": "string",
                    "example": "酱"
                },
                "password": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 6,
                    "example": "123456"
                },
                "userName": {
                    "type": "string",
                    "maxLength": 12,
                    "minLength": 4,
                    "example": "test"
                }
            }
        },
        "model.UpdateReadTime": {
            "type": "object",
            "properties": {
                "groupId": {
                    "type": "integer"
                },
                "receiverId": {
                    "type": "string"
                },
                "senderId": {
                    "type": "string"
                }
            }
        },
        "model.UpdateUser": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "用户头像",
                    "type": "string",
                    "example": "https://******.com/aa.png"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string",
                    "example": "123456789@qq.com"
                },
                "gender": {
                    "description": "性别",
                    "type": "integer"
                },
                "intro": {
                    "description": "个人介绍",
                    "type": "string",
                    "example": "个人介绍"
                },
                "nickName": {
                    "description": "用户昵称",
                    "type": "string",
                    "example": "酱"
                }
            }
        },
        "model.User": {
            "type": "object",
            "required": [
                "userName"
            ],
            "properties": {
                "avatar": {
                    "description": "用户头像",
                    "type": "string",
                    "example": "https://******.com/aa.png"
                },
                "createdAt": {
                    "description": "创建时间",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.JsonTime"
                        }
                    ]
                },
                "email": {
                    "description": "邮箱",
                    "type": "string",
                    "example": "123456789@qq.com"
                },
                "gender": {
                    "description": "性别",
                    "type": "integer"
                },
                "id": {
                    "description": "自增id",
                    "type": "integer"
                },
                "intro": {
                    "description": "个人介绍",
                    "type": "string",
                    "example": "个人介绍"
                },
                "isAdmin": {
                    "description": "是否管理员",
                    "type": "boolean",
                    "default": false
                },
                "isLock": {
                    "description": "是否已锁",
                    "type": "boolean",
                    "default": false
                },
                "nickName": {
                    "description": "用户昵称",
                    "type": "string",
                    "example": "酱"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.JsonTime"
                        }
                    ]
                },
                "userId": {
                    "description": "用户唯一id",
                    "type": "string"
                },
                "userName": {
                    "description": "用户名",
                    "type": "string",
                    "maxLength": 12,
                    "minLength": 4,
                    "example": "test"
                }
            }
        },
        "response.ResType": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "default": 0
                },
                "data": {},
                "msg": {
                    "type": "string",
                    "default": "操作成功"
                }
            }
        }
    },
    "securityDefinitions": {
        "Authorization": {
            "description": "jwt token 鉴权",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9600",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Gin-Zone-Api",
	Description:      "zone服务端API服务",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
