// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/base/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "删除用户接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/base.User"
                        }
                    }
                }
            }
        },
        "/base/users": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "用户列表接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "用户列表",
                "parameters": [
                    {
                        "type": "string",
                        "format": "email",
                        "description": "username search by q",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/base.User"
                        }
                    }
                }
            },
            "post": {
                "description": "用户注册接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "注册接口",
                "parameters": [
                    {
                        "description": "需要上传的json",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.MainUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/base.User"
                        }
                    }
                }
            }
        },
        "/base/users/info": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "用户信息接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/base.User"
                        }
                    }
                }
            }
        },
        "/base/users/login": {
            "post": {
                "description": "用户登录接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "登录接口",
                "parameters": [
                    {
                        "description": "需要上传的json",
                        "name": "LoginForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResType"
                        }
                    }
                }
            }
        },
        "/base/users/{id}": {
            "patch": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "修改用户接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "修改用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User.ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "需要上传的json",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.MainUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/base.User"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "base.User": {
            "type": "object",
            "required": [
                "password",
                "userName"
            ],
            "properties": {
                "createdAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "gender": {
                    "description": "性别",
                    "type": "integer"
                },
                "id": {
                    "description": "自增id",
                    "type": "integer"
                },
                "isAdmin": {
                    "description": "是否管理员",
                    "type": "boolean"
                },
                "isLock": {
                    "description": "是否管理员",
                    "type": "boolean"
                },
                "nickName": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "password": {
                    "description": "密码 - 不会json化",
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 6
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "string"
                },
                "userId": {
                    "description": "用户唯一id",
                    "type": "integer"
                },
                "userName": {
                    "description": "用户名",
                    "type": "string",
                    "maxLength": 12,
                    "minLength": 4
                }
            }
        },
        "model.LoginForm": {
            "type": "object",
            "required": [
                "password",
                "userName"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 6
                },
                "userName": {
                    "type": "string",
                    "maxLength": 12,
                    "minLength": 4
                }
            }
        },
        "model.MainUser": {
            "type": "object",
            "required": [
                "password",
                "userName"
            ],
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "gender": {
                    "description": "性别",
                    "type": "integer"
                },
                "isAdmin": {
                    "description": "是否管理员",
                    "type": "boolean"
                },
                "isLock": {
                    "description": "是否管理员",
                    "type": "boolean"
                },
                "nickName": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "password": {
                    "description": "密码 - 不会json化",
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 6
                },
                "userId": {
                    "description": "用户唯一id",
                    "type": "integer"
                },
                "userName": {
                    "description": "用户名",
                    "type": "string",
                    "maxLength": 12,
                    "minLength": 4
                }
            }
        },
        "response.ResType": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "default": 0
                },
                "data": {},
                "msg": {
                    "type": "string",
                    "default": "操作成功"
                }
            }
        }
    },
    "securityDefinitions": {
        "Authorization": {
            "description": "jwt token 鉴权",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9600",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Gin-Zone-Api",
	Description:      "zone服务端API服务",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
