basePath: /api/v1
definitions:
  base.User:
    properties:
      createdAt:
        description: 创建时间
        type: string
      email:
        description: 邮箱
        type: string
      gender:
        description: 性别
        type: integer
      id:
        description: 自增id
        type: integer
      isAdmin:
        description: 是否管理员
        type: boolean
      isLock:
        description: 是否管理员
        type: boolean
      nickName:
        description: 用户昵称
        type: string
      password:
        description: 密码
        type: string
      updatedAt:
        description: 更新时间
        type: string
      userId:
        description: 用户唯一id
        type: integer
      userName:
        description: 用户名
        type: string
    type: object
host: localhost:9600
info:
  contact: {}
  description: zone服务端API服务
  title: Gin-Zone-Api
  version: "1.0"
paths:
  /base/delete/{id}:
    delete:
      consumes:
      - application/json
      description: 删除用户接口
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.User'
      security:
      - Authorization: []
      summary: 删除用户
      tags:
      - 用户模块
  /base/login:
    post:
      consumes:
      - application/json
      description: 用户登录接口
      parameters:
      - description: 需要上传的json
        in: body
        name: user
        schema:
          $ref: '#/definitions/base.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.User'
      summary: 登录接口
      tags:
      - 用户模块
  /base/register:
    post:
      consumes:
      - application/json
      description: 用户注册接口
      parameters:
      - description: 需要上传的json
        in: body
        name: user
        schema:
          $ref: '#/definitions/base.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.User'
      summary: 注册接口
      tags:
      - 用户模块
  /base/users:
    get:
      consumes:
      - application/json
      description: 用户列表接口
      parameters:
      - description: username search by q
        format: email
        in: query
        name: q
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.User'
      security:
      - Authorization: []
      summary: 用户列表
      tags:
      - 用户模块
  /base/users/{id}:
    get:
      consumes:
      - application/json
      description: 用户信息接口
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.User'
      security:
      - Authorization: []
      summary: 用户信息
      tags:
      - 用户模块
securityDefinitions:
  Authorization:
    description: jwt token 鉴权
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
