basePath: /api/v1
definitions:
  base.FileInfo:
    properties:
      filename:
        type: string
      url:
        type: string
    type: object
  base.Third:
    type: object
  base.User:
    properties:
      avatar:
        description: 用户头像
        example: https://******.com/aa.png
        type: string
      createdAt:
        description: 创建时间
        type: string
      email:
        description: 邮箱
        example: 123456789@qq.com
        type: string
      gender:
        description: 性别
        type: integer
      id:
        description: 自增id
        type: integer
      intro:
        description: 个人介绍
        example: 个人介绍
        type: string
      isAdmin:
        default: false
        description: 是否管理员
        type: boolean
      isLock:
        default: false
        description: 是否已锁
        type: boolean
      nickName:
        description: 用户昵称
        example: 酱
        type: string
      password:
        description: 密码 - 不会json化
        example: "123456"
        maxLength: 16
        minLength: 6
        type: string
      updatedAt:
        description: 更新时间
        type: string
      userId:
        description: 用户唯一id
        type: string
      userName:
        description: 用户名
        example: test
        maxLength: 12
        minLength: 4
        type: string
    required:
    - password
    - userName
    type: object
  model.ChangePassword:
    properties:
      newPassword:
        example: "123456"
        maxLength: 16
        minLength: 6
        type: string
      password:
        example: "123456"
        maxLength: 16
        minLength: 6
        type: string
      userName:
        example: test
        maxLength: 12
        minLength: 4
        type: string
    required:
    - newPassword
    - password
    - userName
    type: object
  model.ChatFriends:
    properties:
      createdAt:
        description: 创建时间
        type: string
      friendId:
        type: string
      groupId:
        type: integer
      id:
        description: 自增id
        type: integer
      updatedAt:
        description: 更新时间
        type: string
      userId:
        type: string
    type: object
  model.ChatGroup:
    properties:
      createdAt:
        description: 创建时间
        type: string
      groupName:
        type: string
      id:
        description: 自增id
        type: integer
      intro:
        type: string
      notice:
        type: string
      updatedAt:
        description: 更新时间
        type: string
      userId:
        type: string
    type: object
  model.ChatGroupMember:
    properties:
      createdAt:
        description: 创建时间
        type: string
      groupId:
        type: integer
      id:
        description: 自增id
        type: integer
      updatedAt:
        description: 更新时间
        type: string
      userId:
        type: string
    type: object
  model.ChatLog:
    properties:
      content:
        type: string
      createdAt:
        description: 创建时间
        type: string
      groupId:
        type: integer
      id:
        description: 自增id
        type: integer
      logType:
        type: integer
      msgType:
        type: integer
      receiverId:
        type: string
      remark:
        type: string
      senderId:
        type: string
      updatedAt:
        description: 更新时间
        type: string
    type: object
  model.ChatLogQuery:
    properties:
      content:
        example: ""
        type: string
      groupId:
        type: integer
      page:
        example: 1
        type: integer
      pageSize:
        example: 20
        type: integer
      receiverId:
        type: string
      senderId:
        type: string
    type: object
  model.LoginForm:
    properties:
      password:
        example: "123456"
        maxLength: 16
        minLength: 6
        type: string
      userName:
        example: test
        maxLength: 12
        minLength: 4
        type: string
    required:
    - password
    - userName
    type: object
  model.MainUser:
    properties:
      avatar:
        description: 用户头像
        example: https://******.com/aa.png
        type: string
      email:
        description: 邮箱
        example: 123456789@qq.com
        type: string
      gender:
        description: 性别
        type: integer
      intro:
        description: 个人介绍
        example: 个人介绍
        type: string
      isAdmin:
        default: false
        description: 是否管理员
        type: boolean
      isLock:
        default: false
        description: 是否已锁
        type: boolean
      nickName:
        description: 用户昵称
        example: 酱
        type: string
      password:
        description: 密码 - 不会json化
        example: "123456"
        maxLength: 16
        minLength: 6
        type: string
      userId:
        description: 用户唯一id
        type: string
      userName:
        description: 用户名
        example: test
        maxLength: 12
        minLength: 4
        type: string
    required:
    - password
    - userName
    type: object
  model.UpdateUser:
    properties:
      avatar:
        description: 用户头像
        example: https://******.com/aa.png
        type: string
      email:
        description: 邮箱
        example: 123456789@qq.com
        type: string
      gender:
        description: 性别
        type: integer
      intro:
        description: 个人介绍
        example: 个人介绍
        type: string
      nickName:
        description: 用户昵称
        example: 酱
        type: string
    type: object
  response.ResType:
    properties:
      code:
        default: 0
        type: integer
      data: {}
      msg:
        default: 操作成功
        type: string
    type: object
host: localhost:9600
info:
  contact: {}
  description: zone服务端API服务
  title: Gin-Zone-Api
  version: "1.0"
paths:
  /base/auth/wxlogin:
    get:
      consumes:
      - application/json
      description: 微信授权登录
      parameters:
      - description: 用户apiid
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.User'
      summary: 微信授权登录
      tags:
      - 用户模块
  /base/upload:
    post:
      consumes:
      - application/json
      description: 上传接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.FileInfo'
      summary: 上传接口
      tags:
      - 基础模块
  /base/users:
    get:
      consumes:
      - application/json
      description: 用户列表接口
      parameters:
      - description: username search by q
        format: email
        in: query
        name: q
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/base.User'
            type: array
      security:
      - Authorization: []
      summary: 用户列表
      tags:
      - 用户模块
    post:
      consumes:
      - application/json
      description: 用户注册接口
      parameters:
      - description: 需要上传的json
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.MainUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.User'
      summary: 注册接口
      tags:
      - 用户模块
  /base/users/{id}:
    delete:
      consumes:
      - application/json
      description: 删除用户接口
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.User'
      security:
      - Authorization: []
      summary: 删除用户
      tags:
      - 用户模块
    patch:
      consumes:
      - application/json
      description: 修改用户接口
      parameters:
      - description: User.ID
        in: path
        name: id
        required: true
        type: integer
      - description: 需要上传的json
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UpdateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UpdateUser'
      security:
      - Authorization: []
      summary: 修改用户信息
      tags:
      - 用户模块
  /base/users/info:
    get:
      consumes:
      - application/json
      description: 用户信息接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.User'
      security:
      - Authorization: []
      summary: 用户信息
      tags:
      - 用户模块
  /base/users/login:
    post:
      consumes:
      - application/json
      description: 用户登录接口
      parameters:
      - description: 需要上传的json
        in: body
        name: LoginForm
        required: true
        schema:
          $ref: '#/definitions/model.LoginForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResType'
      summary: 登录接口
      tags:
      - 用户模块
  /base/users/password:
    post:
      consumes:
      - application/json
      description: 修改密码接口
      parameters:
      - description: 需要上传的json
        in: body
        name: LoginForm
        required: true
        schema:
          $ref: '#/definitions/model.ChangePassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResType'
      security:
      - Authorization: []
      summary: 修改密码
      tags:
      - 用户模块
  /mobile/chat/friends:
    get:
      consumes:
      - application/json
      description: 好友列表
      parameters:
      - description: User.ID
        in: query
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResType'
      summary: 好友列表
      tags:
      - 聊天模块
    post:
      consumes:
      - application/json
      description: 添加好友
      parameters:
      - description: 需要上传的json
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.ChatFriends'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ChatFriends'
      summary: 添加好友
      tags:
      - 聊天模块
  /mobile/chat/groupMembers:
    get:
      consumes:
      - application/json
      description: 群成员列表
      parameters:
      - description: ChatGroup.ID
        in: query
        name: groupId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResType'
      summary: 群成员列表
      tags:
      - 聊天模块
    post:
      consumes:
      - application/json
      description: 添加群成员
      parameters:
      - description: 需要上传的json
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.ChatGroupMember'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ChatGroupMember'
      summary: 添加群成员
      tags:
      - 聊天模块
  /mobile/chat/groups:
    get:
      consumes:
      - application/json
      description: 群组列表
      parameters:
      - description: User.ID
        in: query
        name: userId
        type: integer
      - description: Group.groupName
        in: query
        name: groupName
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResType'
      summary: 群组列表
      tags:
      - 聊天模块
    post:
      consumes:
      - application/json
      description: 添加群组
      parameters:
      - description: 需要上传的json
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.ChatGroup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ChatGroup'
      summary: 添加群组
      tags:
      - 聊天模块
  /mobile/chat/logs:
    post:
      consumes:
      - application/json
      description: 聊天记录
      parameters:
      - description: 需要上传的json
        in: body
        name: query
        required: true
        schema:
          $ref: '#/definitions/model.ChatLogQuery'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ChatLog'
            type: array
      security:
      - Authorization: []
      summary: 聊天记录
      tags:
      - 聊天模块
  /third/gushici:
    get:
      consumes:
      - application/json
      description: 今日古诗词
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.Third'
      summary: 今日古诗词
      tags:
      - 第三方模块
securityDefinitions:
  Authorization:
    description: jwt token 鉴权
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
